[package]
name = "brooke/roblox-project-template"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
React = "jsdotlua/react@17.1.0"
ReactRoblox = "jsdotlua/react-roblox@17.1.0"
react-hooks = "brinkokevin/react-hooks@0.3.1"
knit = "sleitnick/knit@1.7.0"
janitor = "howmanysmall/janitor@1.18.3"
testez = "roblox/testez@0.4.1"
promise = "evaera/promise@4.0.0"
cmdr = "evaera/cmdr@1.12.0"
Signal = "sleitnick/signal@1.0.1"
Fusion = "elttob/fusion@0.2.0"